<a href="https://colab.research.google.com/github/bhushanbadole02/newlp/blob/main/a3naive.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from sklearn.naive_bayes import GaussianNB

In [ ]:
# --------------------------
# 1. Load Dataset
# --------------------------
data = load_iris()
X = data.data
y = data.target

In [ ]:
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [ ]:
# ----------------------------------------------------
# 2. Custom Naive Bayes Classifier (From Scratch)
# ----------------------------------------------------
class CustomNaiveBayes:

    def fit(self, X, y):
        self.classes = np.unique(y)
        self.mean = {}
        self.var = {}
        self.priors = {}

        for c in self.classes:
            X_c = X[y == c]
            self.mean[c] = np.mean(X_c, axis=0)
            self.var[c] = np.var(X_c, axis=0)
            self.priors[c] = X_c.shape[0] / X.shape[0]

    def gaussian_probability(self, class_idx, x):
        mean = self.mean[class_idx]
        var = self.var[class_idx]

        numerator = np.exp(- (x - mean)**2 / (2 * var))
        denominator = np.sqrt(2 * np.pi * var)
        return numerator / denominator

    def predict(self, X):
        y_pred = []
        for x in X:
            posteriors = []

            for c in self.classes:
                prior = np.log(self.priors[c])
                conditional = np.sum(np.log(self.gaussian_probability(c, x)))
                posterior = prior + conditional
                posteriors.append(posterior)

            y_pred.append(self.classes[np.argmax(posteriors)])

        return np.array(y_pred)


In [ ]:
# Train custom model
custom_model = CustomNaiveBayes()
custom_model.fit(X_train, y_train)
custom_pred = custom_model.predict(X_test)

In [ ]:
# ----------------------------------------------------
# 3. Built-in GaussianNB
# ----------------------------------------------------
gnb = GaussianNB()
gnb.fit(X_train, y_train)
builtin_pred = gnb.predict(X_test)

In [ ]:
# ----------------------------------------------------
# 4. Evaluation Function
# ----------------------------------------------------
def evaluate_model(y_true, y_pred, title):
    print("\n-----", title, "-----")
    print("Confusion Matrix:\n", confusion_matrix(y_true, y_pred))
    print("Accuracy:", accuracy_score(y_true, y_pred))
    print("Precision:", precision_score(y_true, y_pred, average='macro'))
    print("Recall:", recall_score(y_true, y_pred, average='macro'))
    print("F1-Score:", f1_score(y_true, y_pred, average='macro'))

In [ ]:
# Evaluate both models
evaluate_model(y_test, custom_pred, "Custom Naive Bayes")
evaluate_model(y_test, builtin_pred, "Built-in GaussianNB")


----- Custom Naive Bayes -----
Confusion Matrix:
 [[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]
Accuracy: 0.9777777777777777
Precision: 0.9761904761904763
Recall: 0.9743589743589745
F1-Score: 0.974320987654321

----- Built-in GaussianNB -----
Confusion Matrix:
 [[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]
Accuracy: 0.9777777777777777
Precision: 0.9761904761904763
Recall: 0.9743589743589745
F1-Score: 0.974320987654321
